project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "NYC Payroll Data Analysis"
  author:
    - Atharva Kulkarni (ak5070)
    - Rameshwar Garg (rg3553)
  repo-url: https://github.com/atharva-011/NYCPayroll
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: morph
    code-fold: true


